### ISSUE TITLE
Add MIT License to Repo Metadata & Header

### ISSUE THREAD

**Issue by TPS** [citp/ad-blocking#3]
I know you've got MIT license ~~buried~~ mentioned @ the bottom of https://github.com/citp/ad-blocking/blob/master/perceptual-adblocker/README.md, but following https://help.github.com/articles/adding-a-license-to-a-repository/ would make it more clear & available for implementation.

TIA! :bow:

---
Done via 2fe946e751cde8f61551a4edb7f79e6a95e3bf2f & 6aa84bee26cde801590bea4a60a01340ab3b6bb2, for the record. 👏

**Comment by storey** [comment]
Done. (There used to be a License file in the perceptual ad blocker as well, but it looks like it got lost during one of the later code restructurings. Thanks for pointing this out!)
