### ISSUE TITLE
does not identify ads on Facebook

### ISSUE THREAD

**Issue by MovGP0** [citp/ad-blocking#6]
Ads on Facebook are not recognized when given in an non-english language. 

![facebook ad](https://cloud.githubusercontent.com/assets/83339/25108879/447614f0-23d9-11e7-9cf2-dc288133932d.png)

**Comment by storey** [comment]
Is this only happening on non-English languages or on the English pages as well? In theory this should be a supported feature, e.g. I just grabbed this screenshot: 

![germanlanguage](https://cloud.githubusercontent.com/assets/3129280/25109231/45d19e8a-23a9-11e7-8060-796dacf97610.png)

I'll continue looking into it.

**Comment by MovGP0** [comment]
it is not working on any ads.  The HTTP header is set to `accept-language:en-US,en;q=0.8,de;q=0.6,de-AT;q=0.4`. Facebook language is set to `de`.

**Comment by MovGP0** [comment]
Update: it works now :-)
